Fetching order data from the server
luanlabs/wagent-payment pull request #12
Opened 2024-09-10 12:00 UTC by dousdogukan

Fetching order data from the server and displaying them.
implement Loading and 404NotFound Pages,
add CTokenLabel component,
add Method class.

2024-09-13 19:39 UTC, ruveyda-kisla approved these changes

2024-09-14 15:17 UTC, ceydae requested changes

2024-09-14 15:17 UTC, ceydae commented on src/App.tsx
> +const methodTabs = ['single', 'stream', 'vesting'];
move to file in src/constant/methods.ts

2024-09-14 15:17 UTC, ceydae commented on src/App.tsx
> +  const { loading, loadingTime, data, error } = useGetOrderData(id);
remove loadingTime

2024-09-14 15:17 UTC, ceydae commented on src/App.tsx
>        setEmailAddress(e.target.value);
add else condition for error message

2024-09-14 15:17 UTC, ceydae commented on src/App.tsx
> +              src={data.user.logo}
use default logo here

2024-09-14 15:17 UTC, ceydae commented on src/containers/Loading/index.tsx
> +const Loading = ({ loadingTime }: LoadingProp) => {
remove loadingTime, use a constant value of 2 seconds for loading

2024-09-14 15:17 UTC, ceydae commented on src/containers/Loading/index.tsx
> +const Loading = ({ loadingTime }: LoadingProp) => {
you can use animation for the progress bar

2024-09-14 15:17 UTC, ceydae commented on src/main.tsx
> +        <Route path="/" element={<App />} />
remove this line

2024-09-14 15:17 UTC, ceydae commented on src/utils/getOrderData.ts
> +      }
remove the code

2024-09-19 17:08 UTC, ceydae approved these changes

2024-09-19 17:09 UTC, merged