Complete payment v2
luanlabs/wagent-payment pull request #19
Opened 2024-12-17 18:14 UTC by dousdogukan

- Completing the payment process.
- Using Redux to manage data fetched from the server (data updates every 3 seconds and is stored in Redux).
- Completing the canceledBox and ExpiredBox components.
- Finalizing the successful page (a download receipt button has been added to this page).
- In Step 3, the wallet address is fetched from the .env file, and its corresponding QR code is generated and displayed.
- Code for Step 4 has been revised, optimized, and improved.
- Z-index issues have been resolved.

2024-12-18 09:14 UTC, ceydae requested changes

2024-12-18 09:14 UTC, ceydae commented on package.json
> +    "@types/qrcode": "^1.5.5",
move to devDependencies

2024-12-18 09:14 UTC, ceydae commented on src/components/Modal/index.tsx
bring back the transition and motions.

2024-12-18 09:14 UTC, ceydae commented on src/App.tsx
add a line here and say `if (!id) { return <NotFound /> }`

and fix all the `id || ''` after that.

2024-12-18 09:14 UTC, ceydae commented on src/containers/PaymentGatewayMultiStep/index.tsx
> +                    <StepThree
rename StepOne, StepTwo and StepThree, etc.. to a meaningful name.

2024-12-18 09:14 UTC, ceydae commented on src/containers/Steps/StepThree/index.tsx
remove unnecessayr blank line

2024-12-18 09:14 UTC, ceydae commented on src/containers/Steps/StepThree/index.tsx
> +
remove unnecessay blank line

2024-12-18 09:14 UTC, ceydae commented on src/containers/Steps/StepThree/index.tsx
> +  };
remove the function and put all the code in the useEffect directly as it only gets called once.

2024-12-18 09:14 UTC, ceydae commented on src/hooks/useOrderData.ts
> +        const { data } = await getOrderDataRequest(id);
if data is marked as `status: completed`, stop the interval until the id changes (using useEffect for example)

2024-12-20 09:08 UTC, ruveyda-kisla commented on package.json
>      "framer-motion": "^11.11.17",
if you decided to remove framer motion uninstall it too.

2024-12-20 09:36 UTC, ruveyda-kisla requested changes
after transaction loading for step 4 was not seen, so when thats fixed or explained I'll review again.

2025-01-28 17:09 UTC, merged