5 select component
luanlabs/wagent-payment pull request #6
Opened 2024-05-26 12:33 UTC by ruveyda-kisla

for #5 

- Added `react-select` package.
- Implemented `CSelect` component.
- Implemented custom styles for `Select`.

2024-05-26 17:38 UTC, dousdogukan commented on src/components/CSelect/index.tsx
Add onChange to return the selected value.

2024-05-27 12:46 UTC, ceydae requested changes
Create a simulation of calling the API in a hook and return an array of objects. 
The objects should contain a property called `logo` which is a URL for an image.
Use the logos in the select tags

2024-06-01 21:25 UTC, ceydae approved these changes

2024-06-02 08:15 UTC, dousdogukan approved these changes

2024-06-02 13:56 UTC, merged